all_flag – DSCF-1224/gmsh_msh1_reader_fortran
all_flag Function
MIT
experimental
5 statements
Source File
private elemental function all_flag(mesh_data)
If any of the flags is .false., it indicates that the file read operation failed.
Arguments
Type Intent Optional Attributes Name
type(gmsh_msh1_data_type), intent(in) :: mesh_data
Return Value logical
Called by
Source Code
    elemental function all_flag(mesh_data)
        type(gmsh_msh1_data_type), intent(in) :: mesh_data
        logical :: all_flag
        all_flag =     mesh_data%flag_nod_section_header    &!
        &        .and. mesh_data%flag_number_of_nodes       &!
        &        .and. mesh_data%flag_deallocation_nodes    &!
        &        .and. mesh_data%flag_allocation_nodes      &!
        &        .and. mesh_data%flag_reading_nodes         &!
        &        .and. mesh_data%flag_nod_section_footer    &!
        &        .and. mesh_data%flag_elm_section_header    &!
        &        .and. mesh_data%flag_number_of_elements    &!
        &        .and. mesh_data%flag_deallocation_elements &!
        &        .and. mesh_data%flag_allocation_elements   &!
        &        .and. mesh_data%flag_reading_elements      &!
        &        .and. mesh_data%flag_elm_section_footer
    end function all_flag
Call graph
is_read_successful_gmsh_msh1_file calls all_flag
is_read_successful calls is_read_successful_gmsh_msh1_file
validate_gmsh_msh1_data calls is_read_successful, validate, validate_gmsh_msh1_element_with_mesh_data_private
validate_gmsh_msh1_element_with_mesh_data_public calls is_read_successful, validate_gmsh_msh1_element_with_mesh_data_private
validate calls validate_gmsh_msh1_data, validate_gmsh_msh1_element_with_mesh_data_public, validate_gmsh_msh1_element_without_mesh_data, validate_gmsh_msh1_node
validate_gmsh_msh1_element_with_mesh_data_private calls validate
validate_gmsh_msh1_element_without_mesh_data calls validate
validate_gmsh_msh1_node calls validate