clear_msg – DSCF-1224/gmsh_msh1_reader_fortran
clear_msg Subroutine
MIT
experimental
4 statements
Source File
private subroutine clear_msg(msg)
Arguments
Type Intent Optional Attributes Name
character(len=msg_len), intent(inout) :: msg
Called by
Source Code
    subroutine clear_msg(msg)
        character(len = msg_len), intent(inout) :: msg
        msg(:) = repeat( ' ' , msg_len )
    end subroutine clear_msg
Call graph
read_gmsh_msh1_ascii_file calls clear_msg, read_gmsh_msh1_ascii_file_kernel
read_gmsh_msh1_element calls clear_msg
read_gmsh_msh1_node calls clear_msg
read_ascii_file calls read_gmsh_msh1_ascii_file
read_gmsh_msh1_ascii_file_kernel calls read_gmsh_msh1_element, read_gmsh_msh1_node