fetch_element_from_loc_gmsh_msh1_file – DSCF-1224/gmsh_msh1_reader_fortran
fetch_element_from_loc_gmsh_msh1_file Subroutine
MIT
experimental
14 statements
Source File
private subroutine fetch_element_from_loc_gmsh_msh1_file(mesh_data, loc, element, stat, errmsg)
Warning
If no element corresponding to the loc argument exists, a element initialized by initialize_gmsh_msh1_element will be returned.
Arguments
Type Intent Optional Attributes Name
type(gmsh_msh1_data_type), intent(in) :: mesh_data
integer, intent(in) :: loc
location in element
type(gmsh_msh1_element_type), intent(inout) :: element
integer, intent(out) :: stat
character(len=*), intent(inout) :: errmsg
Calls
Called by
Source Code
    subroutine fetch_element_from_loc_gmsh_msh1_file(mesh_data, loc, element, stat, errmsg)
        type(gmsh_msh1_data_type), intent(in) :: mesh_data
        !> location in [[gmsh_msh1_data_type:element]]
        integer, intent(in) :: loc
        type(gmsh_msh1_element_type), intent(inout) :: element
        integer, intent(out) :: stat
        character(len=*), intent(inout) :: errmsg
        if (loc .lt. 1) then
            call initialize_gmsh_msh1_element( element, stat, errmsg(:) )
        else if ( output_number_of_elements(mesh_data) .lt. loc ) then
            call initialize_gmsh_msh1_element( element, stat, errmsg(:) )
        else
            element = mesh_data%element(loc)
        end if
    end subroutine fetch_element_from_loc_gmsh_msh1_file
Call graph
fetch_element_from_loc_gmsh_msh1_file calls output_number_of_elements, initialize_gmsh_msh1_element
output_number_of_elements calls output_number_of_elements_gmsh_msh1_file
fetch_element_from_loc calls fetch_element_from_loc_gmsh_msh1_file