findloc_gmsh_msh1_node_number – DSCF-1224/gmsh_msh1_reader_fortran
findloc_gmsh_msh1_node_number Function
MIT
experimental
14 statements
Source File
private elemental function findloc_gmsh_msh1_node_number(msh1_data, node_number) result(location)
Returns the location of the gmsh_msh1_node_type corresponding to the node_number argument.
Warning
If no gmsh_msh1_node_type corresponding to the node_number argument exists, zero will be returned.
Arguments
Type Intent Optional Attributes Name
type(gmsh_msh1_data_type), intent(in) :: msh1_data
type(gmsh_msh1_node_number_type), intent(in) :: node_number
Return Value integer
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: itr_node
Source Code
    elemental function findloc_gmsh_msh1_node_number(msh1_data, node_number) result(location)
        type(gmsh_msh1_data_type), intent(in) :: msh1_data
        type(gmsh_msh1_node_number_type), intent(in) :: node_number
        integer :: location
        integer :: itr_node
        location = 0
        if ( .not. allocated(msh1_data%node) ) return
        do itr_node = 1, count_nodes(msh1_data)
            if ( msh1_data%node(itr_node)%node_number .eq. node_number ) then
                location = itr_node
                return
            end if
        end do
    end function findloc_gmsh_msh1_node_number
Call graph
findloc_gmsh_msh1_node_number calls count_nodes
count_nodes calls count_nodes_gmsh_msh1_data, count_nodes_gmsh_msh1_element
findloc calls findloc_gmsh_msh1_node_number