initialize_gmsh_msh1_node_number – DSCF-1224/gmsh_msh1_reader_fortran
initialize_gmsh_msh1_node_number Subroutine
MIT
experimental
4 statements
Source File
private elemental subroutine initialize_gmsh_msh1_node_number(node_number)
Arguments
Type Intent Optional Attributes Name
type(gmsh_msh1_node_number_type), intent(out) :: node_number
Called by
Source Code
    elemental subroutine initialize_gmsh_msh1_node_number(node_number)
        type(gmsh_msh1_node_number_type), intent(out) :: node_number
        node_number%number = 0
    end subroutine initialize_gmsh_msh1_node_number
Call graph
initialize_gmsh_msh1_node calls initialize_gmsh_msh1_node_number
output_node_number_gmsh_msh1_element calls initialize_gmsh_msh1_node_number
output_node_number calls output_node_number_gmsh_msh1_element
lookup_node_by_loc_gmsh_msh1_file calls initialize_gmsh_msh1_node
lookup_node_by_num_gmsh_msh1_file calls initialize_gmsh_msh1_node
read_gmsh_msh1_file_kernel calls initialize_gmsh_msh1_node
lookup_node calls lookup_node_by_loc_gmsh_msh1_file, lookup_node_by_num_gmsh_msh1_file
read_gmsh_msh1_file calls read_gmsh_msh1_file_kernel