initialize_gmsh_msh1_node – DSCF-1224/gmsh_msh1_reader_fortran
initialize_gmsh_msh1_node Subroutine
MIT
experimental
7 statements
Source File
private elemental subroutine initialize_gmsh_msh1_node(node)
Arguments
Type Intent Optional Attributes Name
type(gmsh_msh1_node_type), intent(out) :: node
Calls
Called by
Source Code
    elemental subroutine initialize_gmsh_msh1_node(node)
        type(gmsh_msh1_node_type), intent(out) :: node
        call initialize_gmsh_msh1_node_number(node%node_number)
        node%x_coord = ieee_value( node%x_coord, ieee_signaling_nan )
        node%y_coord =             node%x_coord
        node%z_coord =             node%x_coord
    end subroutine initialize_gmsh_msh1_node
Call graph
initialize_gmsh_msh1_node calls initialize_gmsh_msh1_node_number
lookup_node_by_loc_gmsh_msh1_file calls initialize_gmsh_msh1_node
lookup_node_by_num_gmsh_msh1_file calls initialize_gmsh_msh1_node
read_gmsh_msh1_file_kernel calls initialize_gmsh_msh1_node
lookup_node calls lookup_node_by_loc_gmsh_msh1_file, lookup_node_by_num_gmsh_msh1_file
read_gmsh_msh1_file calls read_gmsh_msh1_file_kernel