initialize_gmsh_msh1_element – DSCF-1224/gmsh_msh1_reader_fortran
initialize_gmsh_msh1_element Subroutine
MIT
experimental
12 statements
Source File
private subroutine initialize_gmsh_msh1_element(element, stat, errmsg)
Arguments
Type Intent Optional Attributes Name
type(gmsh_msh1_element_type), intent(inout) :: element
integer, intent(out) :: stat
character(len=*), intent(inout) :: errmsg
Calls
Called by
Source Code
    subroutine initialize_gmsh_msh1_element(element, stat, errmsg)
        type(gmsh_msh1_element_type), intent(inout) :: element
        integer, intent(out) :: stat
        character(len=*), intent(inout) :: errmsg
        call initialize_gmsh_msh1_number(element%elm_number)
        call initialize(element%elm_type)
        element%reg_elem%expression = 0
        element%reg_phys%expression = 0
        if ( allocated(element%node_number_list) ) then
            deallocate( &!
            element%node_number_list , &!
            stat   = stat            , &!
            errmsg = errmsg(:)         &!
            )
        end if
    end subroutine initialize_gmsh_msh1_element
Call graph
initialize_gmsh_msh1_element calls initialize, initialize_gmsh_msh1_number
lookup_element_by_loc_gmsh_msh1_file calls initialize_gmsh_msh1_element
read_gmsh_msh1_element calls initialize_gmsh_msh1_element
lookup_element calls lookup_element_by_loc_gmsh_msh1_file
read_gmsh_msh1_file_kernel calls read_gmsh_msh1_element
read_file_gmsh_msh1 calls read_gmsh_msh1_file_kernel
read_file calls read_file_gmsh_msh1