is_stat_failure – DSCF-1224/gmsh_msh1_reader_fortran
is_stat_failure Function
MIT
experimental
5 statements
Source File
private elemental function is_stat_failure(status)
Arguments
Type Intent Optional Attributes Name
type(gmsh_msh1_status_type), intent(in) :: status
Return Value logical
Called by
Source Code
    elemental function is_stat_failure(status)
        type(gmsh_msh1_status_type), intent(in) :: status
        logical :: is_stat_failure
        is_stat_failure = (status%err%code .ne. stat_success)
    end function is_stat_failure
Call graph
is_read_successful_gmsh_msh1_file calls is_stat_failure
read_gmsh_msh1_ascii_file_kernel calls is_stat_failure, read_gmsh_msh1_element
read_gmsh_msh1_element calls is_stat_failure
is_read_successful calls is_read_successful_gmsh_msh1_file
read_gmsh_msh1_ascii_file calls read_gmsh_msh1_ascii_file_kernel
read_ascii_file calls read_gmsh_msh1_ascii_file
validate_gmsh_msh1_data calls is_read_successful, validate, validate_gmsh_msh1_element_with_mesh_data_private
validate_gmsh_msh1_element_with_mesh_data_public calls is_read_successful, validate_gmsh_msh1_element_with_mesh_data_private
validate calls validate_gmsh_msh1_data, validate_gmsh_msh1_element_with_mesh_data_public, validate_gmsh_msh1_element_without_mesh_data, validate_gmsh_msh1_node
validate_gmsh_msh1_element_with_mesh_data_private calls validate
validate_gmsh_msh1_element_without_mesh_data calls validate
validate_gmsh_msh1_node calls validate