lookup_node_by_num_gmsh_msh1_file – DSCF-1224/gmsh_msh1_reader_fortran
lookup_node_by_num_gmsh_msh1_file Function
MIT
experimental
13 statements
Source File
private elemental function lookup_node_by_num_gmsh_msh1_file(mesh_data, node_number) result(node)
Look up a gmsh_msh1_node_type in the gmsh_msh1_data_type.
Warning
If no gmsh_msh1_node_type corresponding to the node_number argument exists, a gmsh_msh1_node_type initialized by initialize_gmsh_msh1_node will be returned.
Arguments
Type Intent Optional Attributes Name
type(gmsh_msh1_data_type), intent(in) :: mesh_data
type(gmsh_msh1_node_number_type), intent(in) :: node_number
Return Value type(gmsh_msh1_node_type)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: itr_node
Source Code
    elemental function lookup_node_by_num_gmsh_msh1_file(mesh_data, node_number) result(node)
        type(gmsh_msh1_data_type), intent(in) :: mesh_data
        type(gmsh_msh1_node_number_type), intent(in) :: node_number
        type(gmsh_msh1_node_type) :: node
        integer :: itr_node
        do itr_node = 1, output_number_of_nodes(mesh_data)
            if ( mesh_data%node(itr_node)%node_number .eq. node_number ) then
                node = mesh_data%node(itr_node)
                return
            end if
        end do
        call initialize_gmsh_msh1_node(node)
    end function lookup_node_by_num_gmsh_msh1_file
Call graph
lookup_node_by_num_gmsh_msh1_file calls output_number_of_nodes, initialize_gmsh_msh1_node
output_number_of_nodes calls output_number_of_nodes_gmsh_msh1_element, output_number_of_nodes_gmsh_msh1_file
lookup_node calls lookup_node_by_num_gmsh_msh1_file