output_number_of_nodes_gmsh_msh1_file – DSCF-1224/gmsh_msh1_reader_fortran
output_number_of_nodes_gmsh_msh1_file Function
MIT
experimental
5 statements
Source File
private elemental function output_number_of_nodes_gmsh_msh1_file(mesh_data) result(number_of_nodes)
Get the number of gmsh_msh1_node_types in the gmsh_msh1_data_type.
Arguments
Type Intent Optional Attributes Name
type(gmsh_msh1_data_type), intent(in) :: mesh_data
Return Value integer
Called by
Source Code
    elemental function output_number_of_nodes_gmsh_msh1_file(mesh_data) result(number_of_nodes)
        type(gmsh_msh1_data_type), intent(in) :: mesh_data
        integer :: number_of_nodes
        number_of_nodes = size( mesh_data%node(:) )
    end function output_number_of_nodes_gmsh_msh1_file
Call graph
output_number_of_nodes calls output_number_of_nodes_gmsh_msh1_file
lookup_node_by_loc_gmsh_msh1_file calls output_number_of_nodes
lookup_node_by_num_gmsh_msh1_file calls output_number_of_nodes
output_node_number_gmsh_msh1_element calls output_number_of_nodes
lookup_node calls lookup_node_by_loc_gmsh_msh1_file, lookup_node_by_num_gmsh_msh1_file
output_node_number calls output_node_number_gmsh_msh1_element