output_node_from_loc_gmsh_msh1_file – DSCF-1224/gmsh_msh1_reader_fortran
output_node_from_loc_gmsh_msh1_file Function
MIT
experimental
12 statements
Source File
private elemental function output_node_from_loc_gmsh_msh1_file(mesh_data, loc) result(node)
Get the gmsh_msh1_node_type from the gmsh_msh1_data_type.
Warning
If no node corresponding to the loc argument exists, a node initialized by initialize_gmsh_msh1_node will be returned.
Arguments
Type Intent Optional Attributes Name
type(gmsh_msh1_data_type), intent(in) :: mesh_data
integer, intent(in) :: loc
location in node
Return Value type(gmsh_msh1_node_type)
Calls
Called by
Source Code
    elemental function output_node_from_loc_gmsh_msh1_file(mesh_data, loc) result(node)
        type(gmsh_msh1_data_type), intent(in) :: mesh_data
        !> location in [[gmsh_msh1_data_type:node]]
        integer, intent(in) :: loc
        type(gmsh_msh1_node_type) :: node
        if (loc .lt. 1) then
            call initialize_gmsh_msh1_node(node)
        else if ( output_number_of_nodes(mesh_data) .lt. loc ) then
            call initialize_gmsh_msh1_node(node)
        else
            node = mesh_data%node(loc)
        end if
    end function output_node_from_loc_gmsh_msh1_file
Call graph
output_node_from_loc_gmsh_msh1_file calls output_number_of_nodes, initialize_gmsh_msh1_node
output_number_of_nodes calls output_number_of_nodes_gmsh_msh1_element, output_number_of_nodes_gmsh_msh1_file
output_node_from_loc calls output_node_from_loc_gmsh_msh1_file