output_node_number_gmsh_msh1_element – DSCF-1224/gmsh_msh1_reader_fortran
output_node_number_gmsh_msh1_element Function
MIT
experimental
12 statements
Source File
private elemental function output_node_number_gmsh_msh1_element(element, location) result(node_number)
Get the gmsh_msh1_node_number_type from the gmsh_msh1_node_type (as derived type).
Warning
If no gmsh_msh1_node_number_type corresponding to the location argument exists, a gmsh_msh1_node_number_type initialized by initialize_gmsh_msh1_node_number will be returned.
Arguments
Type Intent Optional Attributes Name
type(gmsh_msh1_element_type), intent(in) :: element
integer, intent(in) :: location
location in node_number_list
Return Value type(gmsh_msh1_node_number_type)
Calls
Called by
Source Code
    elemental function output_node_number_gmsh_msh1_element(element, location) result(node_number)
        type(gmsh_msh1_element_type), intent(in) :: element
        !> location in [[gmsh_msh1_element_type:node_number_list]]
        integer, intent(in) :: location
        type(gmsh_msh1_node_number_type) :: node_number
        if (location .lt. 1) then
            call initialize_gmsh_msh1_node_number(node_number)
        else if ( output_number_of_nodes(element) .lt. location ) then
            call initialize_gmsh_msh1_node_number(node_number)
        else
            node_number = element%node_number_list(location)
        end if
    end function output_node_number_gmsh_msh1_element
Call graph
output_node_number_gmsh_msh1_element calls output_number_of_nodes, initialize_gmsh_msh1_node_number
output_number_of_nodes calls output_number_of_nodes_gmsh_msh1_element, output_number_of_nodes_gmsh_msh1_file
output_node_number calls output_node_number_gmsh_msh1_element