validate_gmsh_msh1_element_with_mesh_data_private – DSCF-1224/gmsh_msh1_reader_fortran
validate_gmsh_msh1_element_with_mesh_data_private Function
MIT
experimental
8 statements
Source File
private elemental function validate_gmsh_msh1_element_with_mesh_data_private(element, mesh_data) result(is_valid)
Checks if the derived type is valid.
Note
This function does NOT validate mesh_data.
Arguments
Type Intent Optional Attributes Name
type(gmsh_msh1_element_type), intent(in) :: element
type(gmsh_msh1_data_type), intent(in) :: mesh_data
Return Value logical
Calls
Called by
Source Code
    elemental function validate_gmsh_msh1_element_with_mesh_data_private(element, mesh_data) result(is_valid)
        type(gmsh_msh1_element_type), intent(in) :: element
        type(gmsh_msh1_data_type), intent(in) :: mesh_data
        logical :: is_valid
        is_valid = validate(element)
        if (.not. is_valid) return
        is_valid = all( findloc( mesh_data, element%node_number_list(:) ) .ge. minval_location )
    end function validate_gmsh_msh1_element_with_mesh_data_private
Call graph
validate_gmsh_msh1_element_with_mesh_data_private calls validate
validate calls validate_gmsh_msh1_data, validate_gmsh_msh1_element_with_mesh_data_public, validate_gmsh_msh1_element_without_mesh_data, validate_gmsh_msh1_node, validate_gmsh_msh1_number, validate_gmsh_msh1_reg_elem, validate_gmsh_msh1_reg_phys
validate_gmsh_msh1_data calls validate_gmsh_msh1_element_with_mesh_data_private, validate, is_read_successful
validate_gmsh_msh1_element_with_mesh_data_public calls validate_gmsh_msh1_element_with_mesh_data_private, is_read_successful
validate_gmsh_msh1_element_without_mesh_data calls validate
validate_gmsh_msh1_node calls validate
is_read_successful calls is_read_successful_gmsh_msh1_file
is_read_successful_gmsh_msh1_file calls all_flag, is_iostat_failure, is_stat_failure