validate_gmsh_msh1_number – DSCF-1224/gmsh_msh1_reader_fortran
validate_gmsh_msh1_number Function
MIT
experimental
5 statements
Source File
private elemental function validate_gmsh_msh1_number(number) result(is_valid)
Checks if the derived type is valid.
Warning
The number must be a positive (non-zero) integer.
Arguments
Type Intent Optional Attributes Name
class(gmsh_msh1_number_type), intent(in) :: number
Return Value logical
Called by
Source Code
    elemental function validate_gmsh_msh1_number(number) result(is_valid)
        class(gmsh_msh1_number_type), intent(in) :: number
        logical :: is_valid
        is_valid = number%number .gt. 0
    end function validate_gmsh_msh1_number
Call graph
validate calls validate_gmsh_msh1_number, validate_gmsh_msh1_data, validate_gmsh_msh1_element_without_mesh_data, validate_gmsh_msh1_node, validate_gmsh_msh1_element_with_mesh_data_public
validate_gmsh_msh1_data calls validate, validate_gmsh_msh1_element_with_mesh_data_private
validate_gmsh_msh1_element_with_mesh_data_private calls validate
validate_gmsh_msh1_element_without_mesh_data calls validate
validate_gmsh_msh1_node calls validate
validate_gmsh_msh1_element_with_mesh_data_public calls validate_gmsh_msh1_element_with_mesh_data_private