validate_gmsh_msh1_node – DSCF-1224/gmsh_msh1_reader_fortran
validate_gmsh_msh1_node Function
MIT
experimental
7 statements
Source File
private elemental function validate_gmsh_msh1_node(node) result(is_valid)
Checks if the derived type is valid.
Note
Verification by ieee_is_finite is not required by the gmsh documentation.
Arguments
Type Intent Optional Attributes Name
type(gmsh_msh1_node_type), intent(in) :: node
Return Value logical
Calls
Called by
Source Code
    elemental function validate_gmsh_msh1_node(node) result(is_valid)
        type(gmsh_msh1_node_type), intent(in) :: node
        logical :: is_valid
        is_valid = validate(node%node_number)
        if ( .not. is_valid ) return
        is_valid =     ieee_is_finite(node%x_coord) &!
        &        .and. ieee_is_finite(node%y_coord) &!
        &        .and. ieee_is_finite(node%z_coord)
    end function validate_gmsh_msh1_node
Call graph
validate_gmsh_msh1_node calls validate
validate calls validate_gmsh_msh1_node, validate_gmsh_msh1_data, validate_gmsh_msh1_element_with_mesh_data_public, validate_gmsh_msh1_element_without_mesh_data, validate_gmsh_msh1_number, validate_gmsh_msh1_reg_elem, validate_gmsh_msh1_reg_phys
validate_gmsh_msh1_data calls validate, is_read_successful, validate_gmsh_msh1_element_with_mesh_data_private
validate_gmsh_msh1_element_with_mesh_data_public calls is_read_successful, validate_gmsh_msh1_element_with_mesh_data_private
validate_gmsh_msh1_element_without_mesh_data calls validate
is_read_successful calls is_read_successful_gmsh_msh1_file
validate_gmsh_msh1_element_with_mesh_data_private calls validate
is_read_successful_gmsh_msh1_file calls all_flag, is_iostat_failure, is_stat_failure