validate_gmsh_msh1_file – DSCF-1224/gmsh_msh1_reader_fortran
validate_gmsh_msh1_file Function
MIT
experimental
7 statements
Source File
private elemental function validate_gmsh_msh1_file(mesh_data) result(is_valid)
Checks if the derived type is valid.
Arguments
Type Intent Optional Attributes Name
type(gmsh_msh1_data_type), intent(in) :: mesh_data
Return Value logical
Calls
Called by
Variables
Type Visibility Attributes Name Initial
logical, private :: is_invalid
Source Code
    elemental function validate_gmsh_msh1_file(mesh_data) result(is_valid)
        type(gmsh_msh1_data_type), intent(in) :: mesh_data
        logical :: is_valid
        logical :: is_invalid
        is_invalid = &!
            &              is_stat_failure   ( mesh_data%status )   &!
            & .or.         is_iostat_failure ( mesh_data%status )   &!
            & .or. ( .not. all_flag          ( mesh_data        ) )
        is_valid = .not. is_invalid
    end function validate_gmsh_msh1_file
Call graph
validate_gmsh_msh1_file calls all_flag, is_iostat_failure, is_stat_failure
validate calls validate_gmsh_msh1_file, validate_gmsh_msh1_node
validate_gmsh_msh1_node calls validate