validate_gmsh_msh1_element_without_mesh_data – DSCF-1224/gmsh_msh1_reader_fortran
validate_gmsh_msh1_element_without_mesh_data Function
MIT
experimental
13 statements
Source File
private elemental function validate_gmsh_msh1_element_without_mesh_data(element) result(is_valid)
Checks if the derived type is valid.
Note
This function does NOT verify that referenced gmsh_msh1_node_type exist in the mesh.
Arguments
Type Intent Optional Attributes Name
type(gmsh_msh1_element_type), intent(in) :: element
Return Value logical
Calls
Called by
Source Code
    elemental function validate_gmsh_msh1_element_without_mesh_data(element) result(is_valid)
        type(gmsh_msh1_element_type), intent(in) :: element
        logical :: is_valid
        is_valid = validate(element%elm_number)
        if (.not. is_valid) return
        is_valid = validate(element%reg_elem)
        if (.not. is_valid) return
        is_valid = validate(element%reg_phys)
        if (.not. is_valid) return
        is_valid = allocated(element%node_number_list)
        if (.not. is_valid) return
        is_valid = all( validate( element%node_number_list(:) ) )
    end function validate_gmsh_msh1_element_without_mesh_data
Call graph
validate_gmsh_msh1_element_without_mesh_data calls validate
validate calls validate_gmsh_msh1_element_without_mesh_data, validate_gmsh_msh1_data, validate_gmsh_msh1_element_with_mesh_data_public, validate_gmsh_msh1_node, validate_gmsh_msh1_number, validate_gmsh_msh1_reg_elem, validate_gmsh_msh1_reg_phys
validate_gmsh_msh1_data calls validate, is_read_successful, validate_gmsh_msh1_element_with_mesh_data_private
validate_gmsh_msh1_element_with_mesh_data_public calls is_read_successful, validate_gmsh_msh1_element_with_mesh_data_private
validate_gmsh_msh1_node calls validate
is_read_successful calls is_read_successful_gmsh_msh1_file
validate_gmsh_msh1_element_with_mesh_data_private calls validate
is_read_successful_gmsh_msh1_file calls all_flag, is_iostat_failure, is_stat_failure