count_nodes – DSCF-1224/gmsh_msh1_reader_fortran
count_nodes Interface
MIT
experimental
4 statements
Source File
public interface count_nodes
Count the number of gmsh_msh1_node_types.
Calls
Called by
Module Procedures
private elemental function count_nodes_gmsh_msh1_data(mesh_data) result(number_of_nodes)
License
MIT
Version
experimental
Count the number of gmsh_msh1_node_types in the gmsh_msh1_data_type.
Arguments
Type Intent Optional Attributes Name
type(gmsh_msh1_data_type), intent(in) :: mesh_data
Return Value integer
private elemental function count_nodes_gmsh_msh1_element(element) result(number_of_nodes)
License
MIT
Version
experimental
Count the number of gmsh_msh1_node_types in the gmsh_msh1_element_type.
Arguments
Type Intent Optional Attributes Name
type(gmsh_msh1_element_type), intent(in) :: element
Return Value integer
Call graph
count_nodes calls count_nodes_gmsh_msh1_data, count_nodes_gmsh_msh1_element
findloc_gmsh_msh1_node_number calls count_nodes
lookup_node_by_loc_gmsh_msh1_file calls count_nodes
output_node_number_gmsh_msh1_element calls count_nodes
findloc calls findloc_gmsh_msh1_node_number
lookup_node calls lookup_node_by_loc_gmsh_msh1_file
output_node_number calls output_node_number_gmsh_msh1_element