output_node_from_loc – DSCF-1224/gmsh_msh1_reader_fortran
output_node_from_loc Interface
MIT
3 statements
Source File
public interface output_node_from_loc
Get the gmsh_msh1_node_type from the gmsh_msh1_data_type.
Calls
Module Procedures
private elemental function output_node_from_loc_gmsh_msh1_file(mesh_data, loc) result(node)
License
MIT
Version
experimental
Get the gmsh_msh1_node_type from the gmsh_msh1_data_type.
Read more…
Arguments
Type Intent Optional Attributes Name
type(gmsh_msh1_data_type), intent(in) :: mesh_data
integer, intent(in) :: loc
location in node
Return Value type(gmsh_msh1_node_type)
Call graph
output_node_from_loc calls output_node_from_loc_gmsh_msh1_file
output_node_from_loc_gmsh_msh1_file calls output_number_of_nodes, initialize_gmsh_msh1_node
output_number_of_nodes calls output_number_of_nodes_gmsh_msh1_element, output_number_of_nodes_gmsh_msh1_file