output_number_of_nodes – DSCF-1224/gmsh_msh1_reader_fortran
output_number_of_nodes Interface
MIT
experimental
4 statements
Source File
public interface output_number_of_nodes
Get the number of gmsh_msh1_node_types.
Calls
Called by
Module Procedures
private elemental function output_number_of_nodes_gmsh_msh1_element(element) result(number_of_nodes)
License
MIT
Version
experimental
Get the number of gmsh_msh1_node_types in the gmsh_msh1_element_type.
Arguments
Type Intent Optional Attributes Name
type(gmsh_msh1_element_type), intent(in) :: element
Return Value integer
private elemental function output_number_of_nodes_gmsh_msh1_file(mesh_data) result(number_of_nodes)
License
MIT
Version
experimental
Get the number of gmsh_msh1_node_types in the gmsh_msh1_data_type.
Arguments
Type Intent Optional Attributes Name
type(gmsh_msh1_data_type), intent(in) :: mesh_data
Return Value integer
Call graph
output_number_of_nodes calls output_number_of_nodes_gmsh_msh1_element, output_number_of_nodes_gmsh_msh1_file
lookup_node_by_loc_gmsh_msh1_file calls output_number_of_nodes
lookup_node_by_num_gmsh_msh1_file calls output_number_of_nodes
output_node_number_gmsh_msh1_element calls output_number_of_nodes
lookup_node calls lookup_node_by_loc_gmsh_msh1_file, lookup_node_by_num_gmsh_msh1_file
output_node_number calls output_node_number_gmsh_msh1_element