read_file – DSCF-1224/gmsh_msh1_reader_fortran
read_file Interface
MIT
experimental
3 statements
Source File
public interface read_file
Calls
Module Procedures
private subroutine read_file_gmsh_msh1(mesh_data, msh1_file)
License
MIT
Version
experimental
Arguments
Type Intent Optional Attributes Name
type(gmsh_msh1_data_type), intent(inout) :: mesh_data
The read data will be stored in this argument
character(len=*), intent(in) :: msh1_file
File path to read from
Call graph
read_file calls read_file_gmsh_msh1
read_file_gmsh_msh1 calls clear_msg, is_iostat_failure, read_gmsh_msh1_file_kernel
read_gmsh_msh1_file_kernel calls is_iostat_failure, initialize_gmsh_msh1_node, is_iostat_success, is_stat_failure, read_gmsh_msh1_element, read_gmsh_msh1_header_footer, read_gmsh_msh1_node, read_gmsh_msh1_number_of_items
initialize_gmsh_msh1_node calls initialize_gmsh_msh1_number
read_gmsh_msh1_element calls clear_msg, is_iostat_failure, is_stat_failure, initialize_gmsh_msh1_element
read_gmsh_msh1_node calls clear_msg, is_iostat_failure
read_gmsh_msh1_number_of_items calls is_iostat_failure, is_iostat_success
initialize_gmsh_msh1_element calls initialize_gmsh_msh1_number, initialize