validate – DSCF-1224/gmsh_msh1_reader_fortran
validate Interface
MIT
experimental
9 statements
Source File
public interface validate
Checks if the derived type is valid.
Calls
Called by
Module Procedures
private elemental function validate_gmsh_msh1_data(mesh_data) result(is_valid)
License
MIT
Version
experimental
Checks if the derived type is valid.
Arguments
Type Intent Optional Attributes Name
type(gmsh_msh1_data_type), intent(in) :: mesh_data
Return Value logical
private elemental function validate_gmsh_msh1_element_with_mesh_data_public(element, mesh_data) result(is_valid)
License
MIT
Version
experimental
Checks if the derived type is valid.
Arguments
Type Intent Optional Attributes Name
type(gmsh_msh1_element_type), intent(in) :: element
type(gmsh_msh1_data_type), intent(in) :: mesh_data
Return Value logical
private elemental function validate_gmsh_msh1_element_without_mesh_data(element) result(is_valid)
License
MIT
Version
experimental
Checks if the derived type is valid.
Read more…
Arguments
Type Intent Optional Attributes Name
type(gmsh_msh1_element_type), intent(in) :: element
Return Value logical
private elemental function validate_gmsh_msh1_node(node) result(is_valid)
License
MIT
Version
experimental
Checks if the derived type is valid.
Read more…
Arguments
Type Intent Optional Attributes Name
type(gmsh_msh1_node_type), intent(in) :: node
Return Value logical
private elemental function validate_gmsh_msh1_number(number) result(is_valid)
License
MIT
Version
experimental
Checks if the derived type is valid.
Read more…
Arguments
Type Intent Optional Attributes Name
class(gmsh_msh1_number_type), intent(in) :: number
Return Value logical
private elemental function validate_gmsh_msh1_reg_elem(reg_elem) result(is_valid)
License
MIT
Version
experimental
Checks if the derived type is valid.
Read more…
Arguments
Type Intent Optional Attributes Name
type(gmsh_msh1_reg_elem_type), intent(in) :: reg_elem
Return Value logical
private elemental function validate_gmsh_msh1_reg_phys(reg_phys) result(is_valid)
License
MIT
Version
experimental
Checks if the derived type is valid.
Read more…
Arguments
Type Intent Optional Attributes Name
type(gmsh_msh1_reg_phys_type), intent(in) :: reg_phys
Return Value logical
Call graph
validate calls validate_gmsh_msh1_data, validate_gmsh_msh1_element_with_mesh_data_public, validate_gmsh_msh1_element_without_mesh_data, validate_gmsh_msh1_node, validate_gmsh_msh1_number, validate_gmsh_msh1_reg_elem, validate_gmsh_msh1_reg_phys
validate_gmsh_msh1_data calls validate, is_read_successful, validate_gmsh_msh1_element_with_mesh_data_private
validate_gmsh_msh1_element_with_mesh_data_public calls is_read_successful, validate_gmsh_msh1_element_with_mesh_data_private
validate_gmsh_msh1_element_without_mesh_data calls validate
validate_gmsh_msh1_node calls validate
is_read_successful calls is_read_successful_gmsh_msh1_file
validate_gmsh_msh1_element_with_mesh_data_private calls validate
is_read_successful_gmsh_msh1_file calls all_flag, is_iostat_failure, is_stat_failure